---
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource
resources:

- name: IC
  type: pull-request
  check_every: 1m
  source:
    repository: miguelsimon/IC
    access_token: ((github_access_token))

- name: IC_master
  type: git
  source:
    uri: https://github.com/miguelsimon/IC.git
    branch: concourse-ci

jobs:
- name: unit-tests
  serial: true
  plan:
  - get: IC
    trigger: true
    version: every
  - put: IC
    params:
      path: IC
      status: pending
      context: unit-tests
  - task: unit-tests
    file: IC/concourse-ci/run-tests.yml
  on_success:
    do:
      - put: IC
        params:
          path: IC
          status: success
          context: unit-tests
  on_failure:
    do:
      - put: IC
        params:
          path: IC
          status: failure
          context: unit-tests


- name: cluster-tests
  serial: true
  plan:
  - get: IC
    trigger: true
    version: every
    passed:
      - unit-tests
  - get: IC_master
    trigger: true
  - put: IC
    params:
      path: IC
      status: pending
      context: cluster-tests
  - task: cluster-tests
    file: IC/concourse-ci/cluster-tests.yml
    params:
      SSH_PRIVATE_KEY: ((SSH_PRIVATE_KEY))
  on_success:
    do:
      - put: IC
        params:
          path: IC
          status: success
          context: cluster-tests
  on_failure:
    do:
      - put: IC
        params:
          path: IC
          status: failure
          context: cluster-tests
