version: '3'

volumes:
  html-volume:
  letsencrypt-volume:

services:
  concourse-db:
    image: postgres
    environment:
    - POSTGRES_DB=concourse
    - POSTGRES_PASSWORD=concourse_pass
    - POSTGRES_USER=concourse_user
    - PGDATA=/database

  concourse:
    image: concourse/concourse
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    environment:
    - CONCOURSE_POSTGRES_HOST=concourse-db
    - CONCOURSE_POSTGRES_USER=concourse_user
    - CONCOURSE_POSTGRES_PASSWORD=concourse_pass
    - CONCOURSE_POSTGRES_DATABASE=concourse
    - CONCOURSE_EXTERNAL_URL=https://ci.ific-invisible-cities.com
    - CONCOURSE_WORKER_GARDEN_NETWORK
    - CONCOURSE_ADD_LOCAL_USER=test:${CONCOURSE_TEST_PASSWORD}
    - CONCOURSE_MAIN_TEAM_LOCAL_USER=test

  nginx:
    image: nginx:stable
    depends_on: [concourse]
    ports: ["80:80", "443:443"]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - html-volume:/html
      - letsencrypt-volume:/etc/letsencrypt

  make_dummy_certs:
    image: certbot/certbot
    volumes:
      - letsencrypt-volume:/etc/letsencrypt
      - ./nginx/make_dummy_certs.sh:/make_dummy_certs.sh
    entrypoint: /bin/sh
    command: /make_dummy_certs.sh

  erase_certs:
    image: alpine
    volumes:
      - letsencrypt-volume:/etc/letsencrypt
    command: rm -rf /etc/letsencrypt/live/ci.ific-invisible-cities.com

  create_certs:
    image: certbot/certbot
    depends_on: [nginx]
    volumes:
      - html-volume:/html
      - letsencrypt-volume:/etc/letsencrypt
    command: certonly --webroot -w /html -d ci.ific-invisible-cities.com --agree-tos --force-renewal --register-unsafely-without-email

  inspect:
    image: certbot/certbot
    volumes:
      - letsencrypt-volume:/etc/letsencrypt
      - html-volume:/html
    entrypoint: /bin/sh
